name: Build Flutter Web

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Build Flutter Web
        working-directory: /root/projects/Blue-Mobile
        run: |
          git pull
          flutter pub get
          flutter build web --release
